import os
from datetime import datetime

class SREReporter:
    def __init__(self):
        self.report_dir = "./reports"
        os.makedirs(self.report_dir, exist_ok=True)

    def generate_report(self, service: str, diagnosis: str, action_taken: str):
        """Generate a structured Markdown incident report."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{self.report_dir}/incident_report_{service}_{timestamp}.md"
        
        report_content = f"""# Incident Investigation Report

**Service:** {service}
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Status:** Resolved (Remediation executed)

## 1. Executive Summary
An anomaly was detected on the `{service}` service. An autonomous investigation was initiated to retrieve historical context, inspect metrics, and perform remediation.

## 2. Investigation Details
{diagnosis}

## 3. Action Taken / Remediation
{action_taken}

---
*Report generated by Autonomous SRE Agent*
"""
        with open(filename, "w") as f:
            f.write(report_content)
        
        print(f"SUCCESS: Incident report saved to {filename}")
        return filename
